### ISSUE TITLE
scenarios.md unclarity

### ISSUE THREAD

**Issue by lkroesen** [SERG-Delft/jpacman-framework#46]
Written in scenarios.md is:

Scenario S3.2: The ghost moves over food.
Given the game has started,
 and  a ghost is next to a cell containing food;
When  a tick event occurs;
Then  the ghost can move to the food cell,
 and  the food on that cell is not visible anymore.

However, I can not seem to find an implementation of food anywhere in the framework, are pellets meant with "food" ?

**Comment by JeremybellEU** [comment]
Yes, pellets are food. I will create a Pull Request to get this fixed.

**Comment by lkroesen** [comment]
Thanks for the clarification and update.
