### ISSUE TITLE
jpacman-Study

### ISSUE THREAD

**Issue by arcanjo45** [SERG-Delft/jpacman-framework#58]
Hello !! My name is Pedro and I am from Oporto,Portugal.I am currently in the 3rd year of the course of Computer Engineering at FEUP( Engineering College of University of Oporto ) and im doing a work for a class named Software Engineering( ESOF) tha basically consists in studying a open source project avayable on Github. I would like to know if someone could talk me about jpacman testability and how hard or no is to build tests for jpacman and what are the big concerns about testing jpacman functionallity.

Thanks a lot and sorry for any problem i may had cause here.

**Comment by JWGmeligMeyling** [comment]
The jpacman-framework is actually designed for this purpose. During the Software Quality and Engineering course at the Delft University of Technology, students have to write various tests for the framework, and evaluate its testability. The framework is well designed, but there actually are a few end to end scenarios that we came up with that are quite challenging to test.

**Comment by arcanjo45** [comment]
Can you talk me a little bit about that scenarios please?

**Comment by JWGmeligMeyling** [comment]
I have a feeling that figuring out code quality and testability is not just one of our course objectives, but one of yours as well. Look through the code a bit. If you have more concrete questions, I'd be more than willing to answer them!
