### ISSUE TITLE
Investigate dependency resolution issue with JUnit

### ISSUE THREAD

**Issue by TimvdLippe** [SERG-Delft/jpacman-framework#82]
There appears to be a dependency resolution issue with JUnit. Cucumber 1.2.4 requires JUnit 4.11, whereas the framework requires JUnit 4.12.

There seem to be two possible solutions:
1. Exclude the JUnit dependency on Cucumber in the pom.xml
2. ~~Bump cucumber to version 1.2.5-SNAPSHOT which does depend on [JUnit 4.12](https://github.com/cucumber/cucumber-jvm/commit/35dea37900a232d142e6980ab108a6791b542f9f) (originally junit 4.12 broke compatibility with android)~~ See https://github.com/SERG-Delft/jpacman-framework/issues/82#issuecomment-215454113

**Comment by avandeursen** [comment]
I'd say updating the dependency (to 1.2.5-SNAPSHOT) is the best thing to do, and then bump to 1.2.5 as soon as it is available.

**Comment by JWGmeligMeyling** [comment]
Dependency divergence in the minor part of the version number, for test scoped dependencies, doesn't seem any problem to me? Otherwise we would be writing [`[version]`](https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN402) everywhere in our `pom.xml` versions, right?

**Comment by TimvdLippe** [comment]
Option 2 appears to be impossible, as `1.2.5-SNAPSHOT` is not published on the mvn repository and therefore `mvn install` will fail with the message

> [ERROR] Failed to execute goal on project jpacman-framework: Could not resolve dependencies for project nl.tudelft.jpacman:jpacman-framework:jar:6.4.0: The following artifacts could not be resolved: info.cukes:cucumber-java:jar:1.2.5-SNAPSHOT, info.cukes:cucumber-junit:jar:1.2.5-SNAPSHOT: Could not find artifact info.cukes:cucumber-java:jar:1.2.5-SNAPSHOT -> [Help 1]

**Comment by TimvdLippe** [comment]
Cucumber 1.2.5 has been released and [uses JUnit 4.12](https://github.com/cucumber/cucumber-jvm/blob/v1.2.5/pom.xml#L43)

**Comment by TimvdLippe** [comment]
We probably need to see if there again problems with the adoption of JUnit 5 per #99

**Comment by avandeursen** [comment]
Thanks! We're using Cucumber 1.2.5 now, and it works. It does still rely on good old JUnit 4 and its RunWith extensions at the moment, but that works.
