### ISSUE TITLE
Cucumber Interference

### ISSUE THREAD

**Issue by avandeursen** [SERG-Delft/jpacman-framework#83]
The Framework's Cucumber features and step definitions are part of the test jar, which is imported in the template. This has the effect that the same step definitions also apply in solutions based on the template, which is counter intuitive.

A solution might be to drop the test jar dependency in the template.

The 'workaround' now is 
1. To use a uniquely named feature folder in the solution
2. To shadow `nl.tudelft.jpacman.cucubmer.StateNavigationSteps` by having that same package/class  in the solution.

**Comment by JWGmeligMeyling** [comment]
Why include the `test-jar` in the first place? See also this comment: https://github.com/cucumber/cucumber-jvm/issues/999#issuecomment-216536644

**Comment by avandeursen** [comment]
Right. The `test-jar` was there to make some of the (static) methods of the LauncherSmokeTest available, as well as the BasicSquare class (effectively a mock square).

**Comment by avandeursen** [comment]
Thanks! We're using Cucumber 1.2.5 now, and it works. It does still rely on good old JUnit 4 and its RunWith extensions at the moment, but that works.
